# Generated by Django 4.1.3 on 2022-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_alter_plantation_title_alter_sort_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='isable',
            field=models.PositiveBigIntegerField(default=10, verbose_name='Есть в наличии'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
