# Generated by Django 4.1.3 on 2022-11-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_flower_isable_alter_flower_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='isable',
            new_name='isable_count',
        ),
    ]
