# Generated by Django 4.1.3 on 2022-11-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_rename_isable_flower_isable_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='length',
            field=models.CharField(choices=[('30', '30'), ('50', '50'), ('70', '70'), ('90', '90')], max_length=15, verbose_name='Длина'),
        ),
    ]
