# Generated by Django 4.1.3 on 2022-11-08 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='brief_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Был в сети'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Продавец'), ('2', 'Покупатель')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
